# Generated by Django 4.2.24 on 2025-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('livros', 'Livros'), ('apostilas', 'Apostilas'), ('equipamentos', 'Equipamentos'), ('tecnologia', 'Tecnologia')], default='livros', max_length=50),
        ),
    ]
