# Generated by Django 4.2.24 on 2025-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(default='Não informado', help_text='Endereço completo'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL da imagem do produto', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Não informado', help_text='Cidade/Estado', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponível', 'Indisponível'), ('trocado', 'Trocado')], default='disponivel', max_length=255),
        ),
    ]
