# Generated by Django 4.2.24 on 2025-10-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_address_item_image_url_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do produto', null=True, upload_to='item_images/'),
        ),
    ]
