# Generated by Django 4.2.24 on 2025-10-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
    ]
