# Generated by Django 4.2.24 on 2025-09-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_category'),
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='money_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor em dinheiro (se oferta for em dinheiro)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('item', 'Item'), ('money', 'Dinheiro')], default='item', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item_offered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to='items.item'),
        ),
    ]
