# Generated by Django 4.2.24 on 2025-09-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trade_admin',
            field=models.BooleanField(default=False, help_text='Designa se este usuário é um administrador do sistema de trocas'),
        ),
    ]
